// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table hotel_events (event_type:string, event_id:string, event_ts:string, hotel_id:string, hotel_name:string, city:string, booking_id:string, guest_id:string, satisfaction_score:long, minibar_charged:real, late_checkout:bool, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
